/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthUser'];
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['LoginBody'];
        };
      };
      responses: {
        /** @description JWT issued, user returned */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: components['schemas']['AuthUser'];
            };
          };
        };
        /** @description Invalid credentials */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['RegisterBody'];
        };
      };
      responses: {
        /** @description Registered and logged in */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: components['schemas']['AuthUser'];
            };
          };
        };
        /** @description Validation error or already exists */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/install': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Install status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              installed: boolean;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            username: string;
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Installation complete */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: components['schemas']['AuthUser'];
            };
          };
        };
        /** @description Already installed or validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PublicUser'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserSettings'];
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            siteAppearance?: string;
            externalStylesheet?: string | '';
            styledTooltips?: boolean;
            paranoia?: number;
            avatar?: string;
          };
        };
      };
      responses: {
        /** @description Updated current user settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserSettings'] & {
              avatar?: string;
            };
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            userRankId?: number;
          };
        };
      };
      responses: {
        /** @description Created user */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminCreatedUser'];
          };
        };
        /** @description Validation error or duplicate user */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profile/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MyProfile'];
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Profile not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            avatar?: string | '';
            avatarMouseoverText?: string;
            profileTitle?: string;
            profileInfo?: string;
            siteAppearance?: string;
            externalStylesheet?: string | '';
            styledTooltips?: boolean;
          };
        };
      };
      responses: {
        /** @description Updated current user profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MyProfile'];
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Profile not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profile/user/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Public profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PublicProfile'];
          };
        };
        /** @description Profile not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profile/referral/create-invite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            reason?: string;
          };
        };
      };
      responses: {
        /** @description Invite created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              msg: string;
              inviteKey: string;
            };
          };
        };
        /** @description No invites remaining */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Invite already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/home/featured': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Homepage featured content */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              albumOfTheMonth: components['schemas']['HomepageFeaturedAlbum'] &
                unknown;
              vanityHouse: components['schemas']['HomepageFeaturedRelease'] &
                unknown;
            };
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/announcements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description News and blog posts */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'success';
              data: {
                announcements: components['schemas']['Announcement'][];
                blogPosts: {
                  id: number;
                  title: string;
                  createdAt: string;
                }[];
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/forums/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All categories with forums */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: number;
              name: string;
              forums: components['schemas']['Forum'][];
            }[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/forums/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Forum */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Forum'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/forums/{forumId}/topics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: string;
        };
        header?: never;
        path: {
          forumId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated topics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaginatedForumTopics'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          forumId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            title: string;
            body: string;
            question?: string;
            answers?: string;
          };
        };
      };
      responses: {
        /** @description Topic created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ForumTopic'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/forums/{forumId}/topics/{topicId}/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: string;
        };
        header?: never;
        path: {
          forumId: string;
          topicId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated posts */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['ForumPost'][];
              total: number;
              page: number;
              limit: number;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          forumId: string;
          topicId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            body: string;
          };
        };
      };
      responses: {
        /** @description Post created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ForumPost'];
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Topic locked */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/communities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated communities */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['Community'][];
              total: number;
              page: number;
              limit: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/communities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Community */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Community'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/communities/{id}/releases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Releases for community */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['Release'][];
              total: number;
              page: number;
              limit: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: string;
          pageId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Comments */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Comment'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            page: string;
            body: string;
            communityId?: number;
            contributionId?: number;
            artistId?: number;
          };
        };
      };
      responses: {
        /** @description Comment created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Comment'];
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Comment deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Not authorized */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/artists': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All artists */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Artist'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/artists/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Artist with releases and tags */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Artist'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MsgResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    MsgResponse: {
      msg: string;
    };
    ErrorResponse: {
      error: string;
    };
    ValidationError: {
      errors: {
        [key: string]: string[];
      };
    };
    LoginBody: {
      /** Format: email */
      email: string;
      password: string;
    };
    RegisterBody: {
      username: string;
      /** Format: email */
      email: string;
      password: string;
      inviteKey?: string;
    };
    AuthUser: {
      id: number;
      username: string;
      /** Format: email */
      email?: string;
      avatar: string | null;
      inviteCount?: number;
      dateRegistered?: string;
      lastLogin?: string | null;
      isArtist?: boolean;
      isDonor?: boolean;
      canDownload?: boolean;
      userRank: {
        level: number;
        name: string;
        color: string;
        badge?: string;
        permissions?: {
          [key: string]: boolean;
        };
      };
    };
    PublicUser: {
      id: number;
      username: string;
      avatar: string | null;
      dateRegistered: string;
      isArtist: boolean;
      isDonor: boolean;
      userRank: {
        name: string;
        color: string;
      };
      profile: {
        id: number;
        avatar?: string | null;
        avatarMouseoverText?: string | null;
        profileTitle?: string | null;
        profileInfo?: string | null;
      };
    };
    ProfileDetails: {
      id: number;
      avatar?: string | null;
      avatarMouseoverText?: string | null;
      profileTitle?: string | null;
      profileInfo?: string | null;
    };
    UserRankSummary: {
      name: string;
      color: string;
      badge?: string;
    };
    UserSettings: {
      id: number;
      siteAppearance: string;
      externalStylesheet?: string | null;
      styledTooltips: boolean;
      paranoia: number;
    };
    InviteNode: {
      id: number;
      username: string;
      /** Format: email */
      email: string;
      joinedAt: string;
      lastSeen?: string | null;
      uploaded?: string;
      downloaded?: string;
      ratio?: string;
      children?: components['schemas']['InviteNode'][];
    };
    PublicProfile: {
      id: number;
      username: string;
      avatar: string | null;
      dateRegistered: string;
      isArtist: boolean;
      isDonor: boolean;
      userRank: components['schemas']['UserRankSummary'];
      profile: components['schemas']['ProfileDetails'];
      userSettings: {
        siteAppearance?: string;
        styledTooltips?: boolean;
      };
    };
    MyProfile: {
      id: number;
      username: string;
      avatar: string | null;
      profile: components['schemas']['ProfileDetails'];
      userSettings: components['schemas']['UserSettings'];
      userRank: {
        name: string;
        color: string;
      };
      inviteTree: components['schemas']['InviteNode'][];
    };
    AdminCreatedUser: {
      id: number;
      username: string;
      /** Format: email */
      email: string;
    };
    HomepageFeaturedRelease: {
      id: number;
      title: string;
      year?: number | null;
      image?: string | null;
      communityId: number;
      artist?: {
        id: number;
        name: string;
      } | null;
    };
    HomepageFeaturedAlbum: {
      id: number;
      title: string;
      started: string;
      ended: string;
      threadId?: number | null;
      release: components['schemas']['HomepageFeaturedRelease'];
    };
    Announcement: {
      id: number;
      title: string;
      body: string;
      createdAt: string;
    };
    Forum: {
      id: number;
      name: string;
      description: string;
      numTopics: number;
      numPosts: number;
    };
    ForumTopic: {
      id: number;
      title: string;
      forumId: number;
      authorId: number;
      isLocked: boolean;
      isSticky: boolean;
      numPosts: number;
      createdAt: string;
    };
    ForumPost: {
      id: number;
      forumTopicId: number;
      authorId: number;
      body: string;
      createdAt: string;
      updatedAt: string;
    };
    PaginatedForumTopics: {
      data: components['schemas']['ForumTopic'][];
      total: number;
      page: number;
      limit: number;
    };
    Community: {
      id: number;
      name: string;
      type: string;
      _count?: {
        releases: number;
        contributors: number;
        consumers: number;
      };
    };
    Release: {
      id: number;
      title: string;
      communityId: number | null;
      year: number;
      type: string;
      createdAt: string;
    };
    Comment: {
      id: number;
      page: string;
      body: string;
      authorId: number;
      createdAt: string;
    };
    Artist: {
      id: number;
      name: string;
      vanityHouse: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
